configurations:
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/Testing/
        - Sources/SnapshotTesting/
    templates:
      - .sourcery/template
    output: Sources/Testing/Generated/Sourcery.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkCommon]
